BUSINESS_METRICS_VIEW_CONFIG = {
  'Write HBase' : [['write operation', 'Write/HBase'],
                   ['log length', 'Write/Log'],
                   ['memory/thread', 'Write/MemoryThread'],
  ],
  'Read HBase' : [['read operation', 'Read/HBase'],
                   ['result size', 'Read/ResultSize'],
                   ['memory/thread', 'Read/MemoryThread'],
  ],
}

ONLINE_METRICS_MENU_CONFIG = {
  'Online Write' : [['Qps', 'Write/Qps'],
                    ['HBase Latency', 'Write/HBase Latency'],
                    ['Total Latency', 'Write/Total Latency'],
                    ['WriteFail', 'Write/WriteFail'],
                    ['HTablePool', 'Write/HTablePool'],
                    ['Replication', 'Write/Replication'],
                    ['Exception', 'Write/Exception'],
  ],
  'Online Read' : [['Qps', 'Read/Qps'],
                   ['HBase Latency', 'Read/HBase Latency'],
                   ['Total Latency', 'Read/Total Latency'],
                   ['ReadFail', 'Read/ReadFail'],
                   ['HTablePool', 'Read/HTablePool'],
                   ['Exception', 'Read/Exception'],
  ],
}

ONLINE_METRICS_TITLE_CONFIG = {
  'Online Write' : {'Qps' : ['MiliaoRecent Write Qps from MiliaoServer', 'MiliaoMessage Write Qps from MiliaoServer',
                             'Write Qps from HBase online_recent_miliao Table', 'Write Qps from HBase online_message_miliao Table'],
                    'HBase Latency' : ['MiliaoRecent Write Latency from MiliaoServer', 'MiliaoMessage Write Latency from MiliaoServer',
                                       'MiliaoMessage Write Latency from HBase'],
                    'Total Latency' : ['Miliao access Riak Latency', 'LevelDb & HBase Write Latency from MiliaoServer'],
                    'WriteFail' : ['Riak Write Fail',
                                   'MiliaoRecent Write HBase Fail from MiliaoServer(Not-Retry)',
                                   'MiliaoRecent Write HBase Fail from MiliaoServer(Retry) [This Graph will be Null if No-Fail-With-Retry Happen]',
                                   'MiliaoMessage Write HBase Fail from MiliaoServer(Not-Retry)',
                                   'MiliaoMessage Write HBase Fail from MiliaoServer(Retry) [This Graph will be Null if No-Fail-With-Retry Happen]'],
                    'HTablePool' : ['MiliaoRecent Concurrent Using HTable Count', 'MiliaoRecent Pooled Opened HTable in HTablePool',
                                    'MiliaoMessage Concurrent Using HTablePool Count', 'MiliaoMessage Pooled Opened HTablePool in HTablePool'],
                    'Replication' : ['Scan check success rate', 'Scan check content not same count', 'Get check fail count', 'Get check queue length'],
                    'Exception' : ['Non-HException count', 'Runtime Excepton count', 'Too Long Exception'],
  },
  'Online Read' : {'Qps' : ['Read Qps from MiliaoServer', 'Read Count every 10s from HBase online_recent_miliao Table'],
                   'HBase Latency' : ['Read Latency from MiliaoServer', 'OpenScanner Rpc Latency from HBase', 'Next Rpc Latency from HBase'],
                   'Total Latency' : ['Get Riak Latency', 'LevelDb & HBase Read Latency from MiliaoServer'],
                   'ReadFail' : ['Read HBase Fail from MiliaoServer(Not-Retry)', 'Read HBase Fail from MiliaoServer(Retry)'],
                   'HTablePool' : ['Concurrent Using HTable Count', 'Pooled Opened HTable in HTablePool'],
                   'Exception' : ['Non-HException count', 'Runtime Excepton count', 'Too Long Exception'],
  },
}

#define miliao server endpoint
MILIAO_WRITE_SERVER_ENDPOINT = '10.0.3.53-8926|10.0.3.54-8926'
MILIAO_READ_SERVER_ENDPOINT = '10.0.3.53-8928|10.0.3.54-8928'
HBASE_SDSRV_MILIAO_CLUSTER_ENDPOINT = 'sdsrv-miliao'
HBASE_SDSRV_MILIAO_REGIONSERVER_ENDPOINT = '10.0.4.169-11601|10.0.4.170-11601|10.0.4.171-11601|10.0.4.172-11601|10.0.4.173-11601'
REPLICATION_TOOL_ENDPOINT = '10.0.3.99'

ONLINE_METRICS_ENDPOINT_CONFIG = {
  'Online Write' : {'Qps' : [MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT,
                             HBASE_SDSRV_MILIAO_CLUSTER_ENDPOINT, HBASE_SDSRV_MILIAO_CLUSTER_ENDPOINT],
                    'HBase Latency' : [MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT,
                                       HBASE_SDSRV_MILIAO_REGIONSERVER_ENDPOINT],
                    'Total Latency' : [MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT],
                    'WriteFail' : [MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT,
                                   MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT],
                    'HTablePool' : [MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT,
                                    MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT],
                    'Replication' : [REPLICATION_TOOL_ENDPOINT, REPLICATION_TOOL_ENDPOINT,
                                    REPLICATION_TOOL_ENDPOINT, REPLICATION_TOOL_ENDPOINT, REPLICATION_TOOL_ENDPOINT],
                    'Exception' : [MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT, MILIAO_WRITE_SERVER_ENDPOINT],
  },
  'Online Read' : {'Qps' : [MILIAO_READ_SERVER_ENDPOINT, HBASE_SDSRV_MILIAO_REGIONSERVER_ENDPOINT],
                   'HBase Latency' : [MILIAO_READ_SERVER_ENDPOINT, HBASE_SDSRV_MILIAO_REGIONSERVER_ENDPOINT, HBASE_SDSRV_MILIAO_REGIONSERVER_ENDPOINT],
                   'Total Latency' : [MILIAO_READ_SERVER_ENDPOINT, MILIAO_READ_SERVER_ENDPOINT],
                   'ReadFail' : [MILIAO_READ_SERVER_ENDPOINT, MILIAO_READ_SERVER_ENDPOINT],
                   'HTablePool' : [MILIAO_READ_SERVER_ENDPOINT, MILIAO_READ_SERVER_ENDPOINT],
                   'Exception' : [MILIAO_READ_SERVER_ENDPOINT, MILIAO_READ_SERVER_ENDPOINT, MILIAO_READ_SERVER_ENDPOINT]
  },
}

ONLINE_METRICS_COUNTER_CONFIG = {
  'Online Write' : {'Qps': ['p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_save_msg_success',
                            'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_save_msg_to_message_success',
                            'online_miliao_recent-writeRequestsCountPerSec',
                            'online_miliao_message-writeRequestsCountPerSec'],
                    'HBase Latency' : ['p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-saver_access_hbase_95_percent',
                                       'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-saver_access_hbase_message_95_percent',
                                       'HBase-multiAvgTime'],
                    'Total Latency' : ['p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-saver_access_riak_95_percent',
                                       'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-saver_handle_message_95_percent'],
                    'WriteFail': ['p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-save_riak_failed',
                                  'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_save_msg_failed',
                                  'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_save_msg_failed_after_retry',
                                  'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_save_msg_to_message_failed',
                                  'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_save_msg_to_message_failed_after_retry'],
                    'HTablePool': ['p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_concurrent_using_htable_count',
                                  'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_pooled_htable_count',
                                  'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_message_concurrent_using_htable_count',
                                  'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_message_pooled_htable_count'],
                    'Replication' : ['infra-hbase-replication-sdsrv-miliao-vs-ggsrv-miliao-scan_cmp_success_rate',
                                     'infra-hbase-replication-sdsrv-miliao-vs-ggsrv-miliao-scan_cmp_content_not_same_count_key',
                                     'infra-hbase-replication-sdsrv-miliao-vs-ggsrv-miliao-get_cmp_fail_count',
                                     'infra-hbase-replication-sdsrv-miliao-vs-ggsrv-miliao-get_cmp_queue_length'],
                    'Exception' : ['p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_saver_nohexception_count',
                                   'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_saver_runtimeexception_count',
                                   'p2-com.xiaomi.miliao.thrift.msg.MsgSaverService-msgstorage-hbase_saver_consume_too_long'],
  },
  'Online Read' : {'Qps' : ['p2-com.xiaomi.miliao.thrift.msg.MSGStorage-msgfetch-hbase_fetch_msg_success',
                            'HBase-nextNumOps'],
                   'HBase Latency' : ['p2-com.xiaomi.miliao.thrift.msg.MSGStorage-fetcher_access_hbase_95_percent',
                            'HBase-openScannerAvgTime',
                            'HBase-nextAvgTime'],
                   'Total Latency' : ['p2-com.xiaomi.miliao.thrift.msg.MSGStorage-fetcher_get_riak_95_percent',
                                      'p2-com.xiaomi.miliao.thrift.msg.MSGStorage-fetcher_handle_request_95_percent'],
                   'ReadFail': ['p2-com.xiaomi.miliao.thrift.msg.MSGStorage-msgfetch-hbase_fetch_msg_failed',
                                'p2-com.xiaomi.miliao.thrift.msg.MSGStorage-msgfetch-hbase_fetch_msg_failed_after_retry'],
                   'HTablePool': ['p2-com.xiaomi.miliao.thrift.msg.MSGStorage-msgstorage-hbase_concurrent_using_htable_count',
                                 'p2-com.xiaomi.miliao.thrift.msg.MSGStorage-msgstorage-hbase_pooled_htable_count'],
                   'Exception' : ['p2-com.xiaomi.miliao.thrift.msg.MSGStorage-msgfetch-hbase_fetcher_nohexception_count',
                                  'p2-com.xiaomi.miliao.thrift.msg.MSGStorage-msgfetch-hbase_fetcher_runtimeexception_count',
                                  'p2-com.xiaomi.miliao.thrift.msg.MSGStorage-msgfetch-hbase_fetcher_consume_too_long'],
  }
}
